### ISSUE TITLE
How would I go about writing a manyTill1 implementation?

### ISSUE THREAD

**Issue by tolgap** [elm-community/parser-combinators#22]
I have a segment where I can have any characters except for `;`. But the segment is optional.

Right now I'm using

```
manyTill anyChar (char ';')
```

but this will succeed even if the segment is empty. So I need something like `manyTill1`. What would be the `elm-combine` equivalent of this?

**Comment by stil4m** [comment]
I've created an Ellie for this: https://ellie-app.com/x4vvB9gYnZa1/1

`parser1` is your original example. `parser3` uses this, but adds a bind operator so you can verify the match of the initial combinator and succeed or fail if the match is empty.

`parser2` uses a simple regex. Would one of these solutions work for you?
