### ISSUE TITLE
Runtime exception in recursive parsers (elm compiler bug?)

### ISSUE THREAD

**Issue by turboMaCk** [elm-community/parser-combinators#23]
Hi folks :wave:!

I think I've found bug but also believe this is cased by elm compiler rather that `Combine` itself. Anyway I think it's still good to have a record of this.

This is so far the most minimal example I've managed to find:

```elm
module Parser exposing (..)

import Combine exposing (..)
import Html exposing (Html)


type Expression
    = Node (List Expression)


node : Parser s Expression
node =
    Node
        <$> brackets (many expression)


expression : Parser s Expression
expression =
    Combine.lazy <| \() -> node


parseExpression : String -> Result String Expression
parseExpression s =
    case Combine.parse expression s of
        Ok ( _, _, expr ) ->
            Ok expr

        Err ( _, _, errs ) ->
            Err <| String.join " or " errs


json : String
json =
    """[]"""

main : Html msg
main =
    Html.text <| toString <| parseExpression json
```

I've tried to debug deeply but `undefined` value has been past many times so I didn't manage to identify where it actually happens (yet).

Hope it all make sense.

*update: simpler example*

**Comment by turboMaCk** [comment]
update: I've managed to make example much simpler.

**Comment by turboMaCk** [comment]
This is same issue reproduced by reducing official Scheme parser example:

```elm
module Scheme exposing (..)

import Combine exposing (..)


type E
    = EList (List E)


list : Parser s E
list =
    EList
        <$> parens (many expr)
        <?> "list"


expr : Parser s E
expr =
    lazy <|
        \() ->
            whitespace *> list <* whitespace


program : Parser s (List E)
program =
    manyTill expr end


parse : String -> Result String (List E)
parse s =
    case Combine.parse program s of
        Ok ( _, _, e ) ->
            Ok e

        Err ( _, _, errs ) ->
            Err <| String.join " or " errs


code =
    """()"""


res =
    parse code
```

**Comment by eeue56** [comment]
@turboMaCk it would help a lot if you could also describe the error itself, paste it here.

**Comment by stil4m** [comment]
@turboMaCk I've fixed your issue in an Ellie (https://ellie-app.com/x4K8Ly3g9Na1/2)

You added the lazy to the `expr`, but it was needed on the `list`.
If you have a cyclic reference of combinators. For example: `list -> expr -> list`, it is kind of a best practice to define lazy on each of them.

I believe the issue that causes this problem is [Elm Compiler #1527](https://github.com/elm-lang/elm-compiler/issues/1527).
